export const ORGANIZATION_ASSET_LOGO_MAX_BYTES = 5 * 1024 * 1024;
export const ORGANIZATION_ASSET_WEB_IMAGE_MAX_BYTES = 20 * 1024 * 1024;
export const ORGANIZATION_ASSET_MULTIPART_OVERHEAD_BYTES = 512 * 1024;
export const ORGANIZATION_ASSET_LOGO_MAX_EDGE = 1600;
export const ORGANIZATION_ASSET_WEB_IMAGE_MAX_EDGE = 2400;
export const ORGANIZATION_ASSET_WEB_IMAGE_JPEG_QUALITY = 82;
export const ORGANIZATION_ASSET_MAX_INPUT_PIXELS = 40_000_000;
