import type { PreferredProvider } from "@/features/cotizaciones/services/component-suggestions.service";
import type { PricingMode } from "@/features/cotizaciones/types/pricing-mode";
import type { EntityId } from "@/types/common";

export type HeroMode = "image" | "gradient";
export type PublicScheduleDay = "0" | "1" | "2" | "3" | "4" | "5" | "6";
export type SolicitudPublicaHorarioDia = {
  day: PublicScheduleDay;
  enabled: boolean;
  from: string;
  to: string;
};

export type OrganizationProfile = {
  organizationId: EntityId | null;
  empresaNombre: string;
  empresaLogoUrl: string | null;
  empresaDireccion: string;
  empresaTelefono: string;
  empresaEmail: string;
  brandColor: string;
  formaPago: string;
  solicitudPublicaSlug: string;
  solicitudPublicaDescripcionCorta: string;
  solicitudPublicaValor: string;
  solicitudPublicaMensajeConfianza: string;
  solicitudPublicaPrivacidad: string;
  solicitudPublicaHorarioDesde: string;
  solicitudPublicaHorarioHasta: string;
  solicitudPublicaDiasAtencion: string[];
  solicitudPublicaHorarioPorDia: SolicitudPublicaHorarioDia[];
  proveedorPreferido: PreferredProvider;
  modoPrecioPreferido: PricingMode;
  margenDefecto: number;
  creadoEn: string | null;
  actualizadoEn: string | null;
  publicName: string;
  publicSubtitle: string;
  publicZone: string;
  publicBusinessType: string;
  secondaryColor: string;
  heroMode: HeroMode;
  heroImageUrl: string | null;
  heroTitle: string;
  heroSubtitle: string;
  showGallery: boolean;
  showSchedule: boolean;
  showRating: boolean;
  ratingLabel: string;
  jobsCountLabel: string;
  formTitle: string;
  formSubtitle: string;
  isPublished: boolean;
};

export type UpdateOrganizationProfileInput = {
  empresaNombre: string;
  empresaLogoUrl: string | null;
  empresaDireccion: string;
  empresaTelefono: string;
  empresaEmail: string;
  brandColor: string;
  formaPago: string;
  solicitudPublicaSlug: string;
  solicitudPublicaDescripcionCorta: string;
  solicitudPublicaValor: string;
  solicitudPublicaMensajeConfianza: string;
  solicitudPublicaPrivacidad: string;
  solicitudPublicaHorarioDesde: string;
  solicitudPublicaHorarioHasta: string;
  solicitudPublicaDiasAtencion: string[];
  solicitudPublicaHorarioPorDia: SolicitudPublicaHorarioDia[];
  proveedorPreferido: PreferredProvider;
  modoPrecioPreferido: PricingMode;
  margenDefecto: number;
  publicName: string;
  publicSubtitle: string;
  publicZone: string;
  publicBusinessType: string;
  secondaryColor: string;
  heroMode: HeroMode;
  heroImageUrl: string | null;
  heroTitle: string;
  heroSubtitle: string;
  showGallery: boolean;
  showSchedule: boolean;
  showRating: boolean;
  ratingLabel: string;
  jobsCountLabel: string;
  formTitle: string;
  formSubtitle: string;
  isPublished: boolean;
};
