-- Preferencia comercial de visualización mm/cm por empresa.
-- Interno (cálculo, persistencia de cotización, recetas y fabricación) sigue en mm.

alter table public.organization_profile
  add column if not exists unidad_medidas text not null default 'mm';

alter table public.organization_profile
  drop constraint if exists organization_profile_unidad_medidas_check;

alter table public.organization_profile
  add constraint organization_profile_unidad_medidas_check
  check (unidad_medidas in ('mm', 'cm'));

comment on column public.organization_profile.unidad_medidas is
  'Unidad de visualizacion comercial para ancho/alto al cotizar. Internamente Ventora sigue usando mm.';

revoke insert, update on table public.organization_profile from authenticated;

grant insert (
  organization_id,
  empresa_nombre,
  empresa_logo_url,
  responsable_comercial,
  country_code,
  currency_code,
  locale,
  timezone,
  phone_country_code,
  tax_label,
  tax_rate_default,
  tax_id_label,
  empresa_direccion,
  empresa_telefono,
  empresa_email,
  brand_color,
  forma_pago,
  solicitud_publica_slug,
  solicitud_publica_descripcion_corta,
  solicitud_publica_valor,
  solicitud_publica_mensaje_confianza,
  solicitud_publica_privacidad,
  solicitud_publica_horario_desde,
  solicitud_publica_horario_hasta,
  solicitud_publica_dias_atencion,
  solicitud_publica_horario_por_dia,
  proveedor_preferido,
  modo_precio_preferido,
  margen_defecto,
  unidad_medidas,
  actualizado_en,
  public_name,
  public_subtitle,
  public_zone,
  public_business_type,
  instagram_url,
  facebook_url,
  tiktok_url,
  website_url,
  public_services,
  final_cta_title,
  final_cta_subtitle,
  final_cta_label,
  business_hours_note,
  secondary_color,
  hero_mode,
  hero_image_url,
  hero_title,
  hero_subtitle,
  show_gallery,
  show_schedule,
  show_rating,
  rating_label,
  jobs_count_label,
  form_title,
  form_subtitle,
  is_published
) on table public.organization_profile to authenticated;

grant update (
  empresa_nombre,
  empresa_logo_url,
  responsable_comercial,
  country_code,
  currency_code,
  locale,
  timezone,
  phone_country_code,
  tax_label,
  tax_rate_default,
  tax_id_label,
  empresa_direccion,
  empresa_telefono,
  empresa_email,
  brand_color,
  forma_pago,
  solicitud_publica_slug,
  solicitud_publica_descripcion_corta,
  solicitud_publica_valor,
  solicitud_publica_mensaje_confianza,
  solicitud_publica_privacidad,
  solicitud_publica_horario_desde,
  solicitud_publica_horario_hasta,
  solicitud_publica_dias_atencion,
  solicitud_publica_horario_por_dia,
  proveedor_preferido,
  modo_precio_preferido,
  margen_defecto,
  unidad_medidas,
  actualizado_en,
  public_name,
  public_subtitle,
  public_zone,
  public_business_type,
  instagram_url,
  facebook_url,
  tiktok_url,
  website_url,
  public_services,
  final_cta_title,
  final_cta_subtitle,
  final_cta_label,
  business_hours_note,
  secondary_color,
  hero_mode,
  hero_image_url,
  hero_title,
  hero_subtitle,
  show_gallery,
  show_schedule,
  show_rating,
  rating_label,
  jobs_count_label,
  form_title,
  form_subtitle,
  is_published
) on table public.organization_profile to authenticated;
