create table if not exists public.cotizacion_line_templates (
  id bigint generated by default as identity primary key,
  organization_id bigint not null,
  nombre text not null,
  precio_m2_sugerido numeric(12,2) not null default 0,
  minimo_cobrable numeric(12,2) not null default 0,
  redondeo_precio numeric(12,2) not null default 1000,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  eliminado_en timestamptz null
);

create index if not exists cotizacion_line_templates_org_sort_idx
  on public.cotizacion_line_templates (organization_id, sort_order, nombre)
  where eliminado_en is null;

alter table public.cotizacion_line_templates enable row level security;

drop policy if exists "cotizacion_line_templates_select_own_org" on public.cotizacion_line_templates;
create policy "cotizacion_line_templates_select_own_org"
  on public.cotizacion_line_templates
  for select
  to authenticated
  using (organization_id = get_org_id());

drop policy if exists "cotizacion_line_templates_insert_own_org" on public.cotizacion_line_templates;
create policy "cotizacion_line_templates_insert_own_org"
  on public.cotizacion_line_templates
  for insert
  to authenticated
  with check (organization_id = get_org_id());

drop policy if exists "cotizacion_line_templates_update_own_org" on public.cotizacion_line_templates;
create policy "cotizacion_line_templates_update_own_org"
  on public.cotizacion_line_templates
  for update
  to authenticated
  using (organization_id = get_org_id())
  with check (organization_id = get_org_id());
