-- Control de visibilidad del IVA en PDF (sin cambiar el cálculo).

alter table public.organization_profile
  add column if not exists mostrar_iva_en_pdf boolean not null default true;

comment on column public.organization_profile.mostrar_iva_en_pdf is
  'Si es true, el PDF muestra neto e IVA por separado. Si es false, solo total final con IVA incluido.';

alter table public.cotizaciones
  add column if not exists mostrar_iva_en_pdf boolean;

comment on column public.cotizaciones.mostrar_iva_en_pdf is
  'Override por cotización de si el PDF muestra el desglose de IVA. Null hereda comportamiento legacy (mostrar).';

revoke insert, update on table public.organization_profile from authenticated;

grant insert (
  organization_id,
  empresa_nombre,
  empresa_logo_url,
  responsable_comercial,
  country_code,
  currency_code,
  locale,
  timezone,
  phone_country_code,
  tax_label,
  tax_rate_default,
  tax_id_label,
  empresa_direccion,
  empresa_telefono,
  empresa_email,
  brand_color,
  forma_pago,
  validez_predeterminada,
  condiciones_venta_predeterminadas,
  terminos_condiciones_predeterminados,
  mostrar_iva_en_pdf,
  solicitud_publica_slug,
  solicitud_publica_descripcion_corta,
  solicitud_publica_valor,
  solicitud_publica_mensaje_confianza,
  solicitud_publica_privacidad,
  solicitud_publica_horario_desde,
  solicitud_publica_horario_hasta,
  solicitud_publica_dias_atencion,
  solicitud_publica_horario_por_dia,
  proveedor_preferido,
  modo_precio_preferido,
  margen_defecto,
  unidad_medidas,
  actualizado_en,
  public_name,
  public_subtitle,
  public_zone,
  public_business_type,
  instagram_url,
  facebook_url,
  tiktok_url,
  website_url,
  public_services,
  final_cta_title,
  final_cta_subtitle,
  final_cta_label,
  business_hours_note,
  secondary_color,
  hero_mode,
  hero_image_url,
  hero_title,
  hero_subtitle,
  show_gallery,
  show_schedule,
  show_rating,
  rating_label,
  jobs_count_label,
  form_title,
  form_subtitle,
  is_published
) on table public.organization_profile to authenticated;

grant update (
  empresa_nombre,
  empresa_logo_url,
  responsable_comercial,
  country_code,
  currency_code,
  locale,
  timezone,
  phone_country_code,
  tax_label,
  tax_rate_default,
  tax_id_label,
  empresa_direccion,
  empresa_telefono,
  empresa_email,
  brand_color,
  forma_pago,
  validez_predeterminada,
  condiciones_venta_predeterminadas,
  terminos_condiciones_predeterminados,
  mostrar_iva_en_pdf,
  solicitud_publica_slug,
  solicitud_publica_descripcion_corta,
  solicitud_publica_valor,
  solicitud_publica_mensaje_confianza,
  solicitud_publica_privacidad,
  solicitud_publica_horario_desde,
  solicitud_publica_horario_hasta,
  solicitud_publica_dias_atencion,
  solicitud_publica_horario_por_dia,
  proveedor_preferido,
  modo_precio_preferido,
  margen_defecto,
  unidad_medidas,
  actualizado_en,
  public_name,
  public_subtitle,
  public_zone,
  public_business_type,
  instagram_url,
  facebook_url,
  tiktok_url,
  website_url,
  public_services,
  final_cta_title,
  final_cta_subtitle,
  final_cta_label,
  business_hours_note,
  secondary_color,
  hero_mode,
  hero_image_url,
  hero_title,
  hero_subtitle,
  show_gallery,
  show_schedule,
  show_rating,
  rating_label,
  jobs_count_label,
  form_title,
  form_subtitle,
  is_published
) on table public.organization_profile to authenticated;
