-- Fase 3: configuracion visual guiada por item de cotizacion
-- Aditivo, multi-tenant, soft delete. config_json es fuente de verdad; svg_markup es cache.

create table if not exists public.cotizacion_item_visual_configs (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations (id) on delete cascade,
  cotizacion_item_id bigint not null references public.cotizacion_items (id) on delete cascade,
  schema_version integer not null default 1,
  config_json jsonb not null default '{}'::jsonb,
  svg_markup text null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  eliminado_en timestamptz null,
  constraint cotizacion_item_visual_configs_schema_version_positive
    check (schema_version > 0)
);

create unique index if not exists cotizacion_item_visual_configs_active_item_uidx
  on public.cotizacion_item_visual_configs (cotizacion_item_id)
  where eliminado_en is null;

create index if not exists cotizacion_item_visual_configs_org_idx
  on public.cotizacion_item_visual_configs (organization_id)
  where eliminado_en is null;

alter table public.cotizacion_item_visual_configs enable row level security;

drop policy if exists "cotizacion_item_visual_configs_select_own_org"
  on public.cotizacion_item_visual_configs;
create policy "cotizacion_item_visual_configs_select_own_org"
  on public.cotizacion_item_visual_configs
  for select
  to authenticated
  using (organization_id = public.get_org_id());

drop policy if exists "cotizacion_item_visual_configs_insert_own_org"
  on public.cotizacion_item_visual_configs;
create policy "cotizacion_item_visual_configs_insert_own_org"
  on public.cotizacion_item_visual_configs
  for insert
  to authenticated
  with check (organization_id = public.get_org_id());

drop policy if exists "cotizacion_item_visual_configs_update_own_org"
  on public.cotizacion_item_visual_configs;
create policy "cotizacion_item_visual_configs_update_own_org"
  on public.cotizacion_item_visual_configs
  for update
  to authenticated
  using (organization_id = public.get_org_id())
  with check (organization_id = public.get_org_id());

grant select, insert, update on public.cotizacion_item_visual_configs to authenticated;
grant usage, select on sequence public.cotizacion_item_visual_configs_id_seq to authenticated;
